### ISSUE TITLE
Unterschiede in PV_bat-loader.yaml und main.yaml, verschiedene eingebettete yaml als auch Auskommentierungen

### ISSUE THREAD

**Issue by bandit7311** [creepystefan/esphome-XY6020#1]
Moin moin,

wie in Überschrift schon beschrieben ist mir aufgefallen dass in deinem programmierten Code relativ viele Stellen auskommentiert sind als auch die beiden yaml Dateien verschiedene zum Teil gleich benannten eingebettete yaml codes benutzen. 

Um Dinge zu vereinfachen wäre es schön wenn du den Code nochmal durchschaust, ebenso würde ich glaub ich beide Sachen in verschiedene Repositories speichern. 

Habe hier auch zwei dieser Module liegen, jedoch möchte ich in einer übergeordneten Steuerung, hier bei mir NodeRed die Regelung verwirklichen und auf den ESP nur die Hardwaresteuerung laufen lassen, Datenaustausch soll via MQTT stattfinden.

Welche Firmwareversion haben deine XY6020L? Hast du schon Messungen bezüglich Wirkungsgrad von den Modulen gemacht? 

Soling
B

**Comment by creepystefan** [comment]
Hey.
Das auskommentierte kommt daher, dass ich erst einen Sensor gemacht habe und dann doch über einen Text_Sensor gegangen bin. 
Ich werde es nochmals anschauen diese Woche, wenn ich Zeit finde.
Du bist der erste der sich für meins interessiert.
Es sollte auch über NodeRed laufen. Da kann ich dir nicht helfen. Ich benutze HomeAssistant.
Habe keine Versuche wegen Grenzen oder Wirkungsgrade oder so gemacht.
Mir reicht es so wie es bei mir aktuell läuft.
Gebe dir dann nochmal Bescheid.

**Comment by creepystefan** [comment]
So, habe einiges angepasst.
Secret.yaml in deine eigene secret.yaml einfügen und anpassen.
du kannst auch natürlich die secret.yaml weglassen, und deine Daten direkt einfügen in die XY6020.yaml
Main.yaml geändert in XY6020.yaml
in der XY6020.yaml natürlich so abändern dass es auf deine Situation angepasst ist.
MQTT, ESP Board information......
Wichtig die TX und RX GPIOS an deine GPIOS anpassen.

möchtest du dann ein ESP Board zur Kommunikation für deine beiden XY6020 laufen lassen
oder mit 2 seperaten ESP Boards. natürlcih musst du dann auch den Namen, IP Adresse, OTA Key, API Key ändern.
entweder OTA_Key2 oder so ähnlich dann in deine Secret.yaml und entsprechend die XY6020.yaml dann für dein 2tes anpassen.

meinen Softwarestand weis ich aktuell nicht, da ich nicht dieses original Sinilink benutze kann ich da eh nichts updaten.
das einzige was komisch ist ist die Model und Versionsnummer. die passen bei vielen leuten nicht die auch z.B. über
Python programme geschrieben haben.

kennst du dich mit ESP Home etwas aus?

Ich würde mich sehr über einen Test und Feedback freuen.
danke

**Comment by bandit7311** [comment]
Hallo Stefan,
habe zwischenzeitlich dein Projekt als Fork.

Finde es gut dass du etwas aufgeräumt hast.

Habe die ganzen verschachtelten Yaml in das Hauptyaml eingefügt und werde das mal so in Betrieb nehmen. 

Softwareversion von deinem XY6020 Board sollte in einem der ausgelesenen Registern stehen, als Ver(sion)

Bei mir wird es am Ende 6-8 dieser XY6020 werden, aus diesem Grund möchte ich auch alles in einem yaml stehen haben, werde das so generieren dass ich nur über die Indexierung des Namens und verändern der IP Adresse eine neues Board betreiben kann. Also z.B. XY6020-1 ... XY6020-2... etc So sollen sich dann auch die ganzen MQTT Topics / Commands unterscheiden.

Die ganzen Spannungs-/Ampere und sich daraus resultierenden Leistungswerte werden in NodeRed aufbereitet und an die ganzen Geräte verteilt. 

Laufen soll es auf einem nackten ESP12 (ohne USB/Ballast) mit einem daran angeschlossenen isolierten Pegelwandlers und jedes XY6020 Modul bekommt einen davon.

Als Visualisierung betreibe ich Openhab. Alle Applikationen (Openhab, NodeRed, ESPHome, etc.) laufen in Docker-Containern.

Bin nicht so der Freund von Verschachtelungen, als auch von lokalen Berechnungen und Querverbindungen, möchte einen Master in dem die Daten ausgewertet, aufbereitet und wieder an die richtigen Stellen geschickt wird. 

Solong 
B

**Comment by creepystefan** [comment]
Das wird nicht so einfach gehen mit dem Namen vom Board ändern.
Die Entitäten (Name der ausgelesene Register) bleiben trotzdem gleich. Kann sein dass es da dann Probleme gibt. Evtl die Namen der Entitäten mit ändern.
Eingangsspannung1 
Eingangsspannung2
Usw......
Musst du ausprobieren.
Ich könnte dir ziemlich schnell eine Lösung bauen, dass man nur einen Wert dafür dann ändern muss.

Man liest oft dass beim xy6020 der CV/CC umschaltmodus nicht passt.
Musste ich leider gestern feststellen.

Wenn ein Akku direkt angeschlossen ist und man Läd z.B. mit 29 durchgehend dann irgendwann die ausgangsspannung an der Batterie 30v übersteigt. Zum Glück kam ein Over Voltage Protect.

Es ist auch zu sehen wenn man mit 29V lädt dass z.B 27,8v Je nach lade Menge, am Ausgang anstehen.
Nimmt man die 29v runter z.B auf 24.5V so geht der Strom natürlich auf 0A. Allerdings sinkt schlagartig die Spannung/Bateriespannung z.B. auf 26,5V.
Da muss ich mal schauen.
Evtl Werde ich die CV/CC Umschaltung gleich in mein Bat-Loader auf dem ESP rein setzen.

Wie ich aktuell über die W-lan ESP Steuerung das Protect resette weis ich noch nicht. Da muss man an dem Bedienpult den Ein und Ausschalt Knopf drücken.

Ich mach mal versuche.

**Comment by bandit7311** [comment]
Ich möchte nicht den Namen vom Board ändern, ich möchte nur den Namen von dem jeweilig angebauten ESP12 durch Indexierung ändern.

Dadurch bekommt jeder einzelne ESP eine individuelle Instanz und lässt sich so einzeln steuern.

Habe mit einem Kollegen das Problem von Umschaltung von CC nach CV besprochen und er hat es getestet, man muss zuerst den Strom und dann direkt die Spannung setzen, dann funktioniert auch das Zurückregeln.

Kannst du mal schauen welche Firmwareversion in den Registern steht?
 Solong
B

**Comment by creepystefan** [comment]
kleine Änderungen.
Version angepasst. wurde bei mir 115 angezeigt, ->> geändert auf 11,5, so habe ich das bei anderen gesehen
der andere hat 11,2 dran stehen. ob es so passt keine Ahnung kann aber auch 1.15 heisen.
Modelbezeichnung funktioniert auch nicht richtig bekomme 61 00 in dem Register.
bei dem anderen der ein XY6015 hat wurde 61 01 angezeigt

in meiner sensor.yaml musst die Version neu rauscopieren und ersetzen.

ebenfalls ist auch ein Reset Button für Protect Status hinzugekommen, um in das Register 0x10 den Wert 0 zu setzen.
Somit wird wenn das Modul selbstständig in einen Over Protect geht zurück gesetzt.

hier die button.yaml benutzen und natürlich in der number.yaml musst bei register 0x10 auch den kompletten Teil nehmen
sonst gehts nicht.

aktuell gibt es leider kein Modbus Controller Button zum setzen, deswegen der Umweg vom Button auf ein Number

**Comment by creepystefan** [comment]
Aktuell gibt es Probleme mit dem Text_Sensor des modbus Controllers seitens ESPHome. Wurde schon gemeldet.
Ich such ne Lösung.

**Comment by bandit7311** [comment]
Moin Stefan, bin momentan etwas eingespannt, gibt es eine andere Möglichkeit als hier um mit dir Kontakt zu halten? Threema vielleicht? Solong B

**Comment by creepystefan** [comment]
Discord kann ich dir anbieten.

**Comment by bandit7311** [comment]
Stefan, wie schaut's aus? Solong B

**Comment by creepystefan** [comment]
Habe erstmal mein bat Loader etwas verfeinert. 
Hast du es schon ausprobiert so wie es jetzt ist.
Probier erstmal ob es so läuft.
Dann können wir Verfeinerungen vornehmen.
Mit dem Text_Sensor habe ich einen Fehler gefunden. Da bin ich noch dran. Aber ist ja erstmal nur ne Anzeige. Hat nichts mit der Steuerung zu tun.

Gib Bescheid ob's läuft.
Kommunikation und so.
Grüße

**Comment by creepystefan** [comment]
Hey Solong
Na wie schaut's aus? Hast du schon einen programmiert?
Bitte um rückinfo
Stefan

**Comment by creepystefan** [comment]
Da du dich nicht mehr meldest, schließe ich das Thema.
